#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Math-Vec
Version  : 1.01
Release  : 10
URL      : https://cpan.metacpan.org/authors/id/E/EW/EWILHELM/Math-Vec-1.01.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/E/EW/EWILHELM/Math-Vec-1.01.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libm/libmath-vec-perl/libmath-vec-perl_1.01-3.debian.tar.xz
Summary  : Object-Oriented Vector Math Methods in Perl
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-Math-Vec-license = %{version}-%{release}
BuildRequires : buildreq-cpan

%description
Math-Vec
INSTALLATION
To install this module, run the following commands:
perl Build.PL
./Build
./Build test
./Build install

%package dev
Summary: dev components for the perl-Math-Vec package.
Group: Development
Provides: perl-Math-Vec-devel = %{version}-%{release}

%description dev
dev components for the perl-Math-Vec package.


%package license
Summary: license components for the perl-Math-Vec package.
Group: Default

%description license
license components for the perl-Math-Vec package.


%prep
%setup -q -n Math-Vec-1.01
cd ..
%setup -q -T -D -n Math-Vec-1.01 -b 1
mkdir -p deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/Math-Vec-1.01/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-Math-Vec
cp deblicense/copyright %{buildroot}/usr/share/package-licenses/perl-Math-Vec/deblicense_copyright
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.28.2/Math/Vec.pm

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Math::Vec.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-Math-Vec/deblicense_copyright
